language: r
cache: packages

r_packages:
  - covr

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get update
  - sudo apt-get install libgdal-dev

after_success:
  - Rscript -e 'library(covr); codecov()'

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
