<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Tune model using AUC • SDMsel</title>
<!-- jquery --><script src="https://code.jquery.com/jquery-3.1.0.min.js" integrity="sha384-nrOSfDHtoPMzJHjVTdCopGqIqeYETSXhZDFyniQ8ZHcVy08QesyHcnOUpMpqnmWq" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script><!-- Font Awesome icons --><link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-T8Gy5hrqNKT+hzMclPo118YTQO6cYprQmhrYwIiQ/3axmI1hQomh7Ud2hPOy8SP1" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/1.7.1/clipboard.min.js" integrity="sha384-cV+rhyOuRHc9Ub/91rihWcGmMmCXDeksTtCihMupQHSsi8GIIRDG0ThDc3HGQFJ3" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../../pkgdown.css" rel="stylesheet">
<script src="../../pkgdown.js"></script><meta property="og:title" content="Tune model using AUC">
<meta property="og:description" content="">
<meta property="og:image" content="/logo.png">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../../index.html">SDMsel</a>
        <span class="label label-danger" data-toggle="tooltip" data-placement="bottom" title="Unreleased package">0.0.0.9000</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../../articles/SDMsel.html">Get started</a>
</li>
<li>
  <a href="../../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../../articles/articles/tune_auc.html">Tune model using AUC</a>
    </li>
  </ul>
</li>
<li>
  <a href="../../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/sgvignali/SDMsel">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><script src="tune_auc_files/htmlwidgets-1.2/htmlwidgets.js"></script><script src="tune_auc_files/plotly-binding-4.8.0/plotly.js"></script><script src="tune_auc_files/typedarray-0.1/typedarray.min.js"></script><script src="tune_auc_files/jquery-1.11.3/jquery.min.js"></script><link href="tune_auc_files/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet">
<script src="tune_auc_files/crosstalk-1.0.0/js/crosstalk.min.js"></script><link href="tune_auc_files/plotly-htmlwidgets-css-1.39.2/plotly-htmlwidgets.css" rel="stylesheet">
<script src="tune_auc_files/plotly-main-1.39.2/plotly-latest.min.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Tune model using AUC</h1>
                        <h4 class="author">Sergio Vignali, Arnaud Barras, Veronika Braunisch</h4>
            
      
      <small class="dont-index">Source: <a href="https://github.com/sgvignali/SDMsel/blob/master/vignettes/articles/tune_auc.Rmd"><code>vignettes/articles/tune_auc.Rmd</code></a></small>
      <div class="hidden name"><code>tune_auc.Rmd</code></div>

    </div>

    
    
<div id="set-working-environment" class="section level1">
<h1 class="hasAnchor">
<a href="#set-working-environment" class="anchor"></a>Set working environment</h1>
<p>Import <code>SDMsel</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">options</span>(<span class="dt">java.parameters =</span> <span class="st">"-Xmx2g"</span> )
<span class="kw">library</span>(SDMsel)
<span class="co">#&gt; Loading required package: zeallot</span>
<span class="co">#&gt; Loading required package: ggplot2</span>
<span class="co">#&gt;  ________________________________________</span>
<span class="co">#&gt; |   ____   ____   __  __             _   |</span>
<span class="co">#&gt; |  / ___| |  _ \ |  \/  | ___   ___ | |  |</span>
<span class="co">#&gt; |  \___ \ | | | || |\/| |/ __| / _ \| |  |</span>
<span class="co">#&gt; |   ___) || |_| || |  | |\__ \|  __/| |  |</span>
<span class="co">#&gt; |  |____/ |____/ |_|  |_||___/ \___||_|  |</span>
<span class="co">#&gt; |________________________________________|</span>
<span class="co">#&gt; </span></code></pre></div>
<p>Load packages used in the vignette:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dismo)      <span class="co"># To download data used in the vignette</span>
<span class="kw">library</span>(plotly)     <span class="co"># For interactive graphs</span>
<span class="kw">library</span>(maps)       <span class="co"># For access useful maps</span>
<span class="kw">library</span>(rasterVis)  <span class="co"># To plot raster objects</span>
<span class="kw">library</span>(gridExtra)  <span class="co"># To plot multiple ggplot object in one page</span></code></pre></div>
</div>
<div id="acquire-environmental-variables-and-species-distribution-data" class="section level1">
<h1 class="hasAnchor">
<a href="#acquire-environmental-variables-and-species-distribution-data" class="anchor"></a>Acquire environmental variables and species distribution data</h1>
<p>For the analysis we will use the climat data from <a href="http://www.worldclim.org/">WorldClim</a> version 1.4 <span class="citation">(Hijmans et al. 2005)</span> (you can download the new version 2.0 from the previous link) and the ecoregions from <a href="https://www.worldwildlife.org/publications/terrestrial-ecoregions-of-the-world">WWF</a> <span class="citation">(Olson et al. 2001)</span> included in the <code>dismo</code> package:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">files &lt;-<span class="st"> </span><span class="kw">list.files</span>(<span class="dt">path =</span> <span class="kw">paste</span>(<span class="kw">system.file</span>(<span class="dt">package =</span> <span class="st">'dismo'</span>), <span class="st">'/ex'</span>, <span class="dt">sep =</span> <span class="st">''</span>), <span class="dt">pattern =</span> <span class="st">'grd'</span>, <span class="dt">full.names =</span> T)
predictors &lt;-<span class="st"> </span><span class="kw">stack</span>(files)</code></pre></div>
<p>Plot <strong>bio1</strong> using <a href="https://www.rdocumentation.org/packages/rasterVis/versions/0.43/topics/gplot-methods">gplot</a> function from <code>rasterVis</code> package:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="http://www.rdocumentation.org/packages/rasterVis/topics/gplot-methods">gplot</a></span>(predictors<span class="op">$</span>bio1) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_tile</span>(<span class="kw">aes</span>(<span class="dt">fill =</span> value)) <span class="op">+</span>
<span class="st">    </span><span class="kw">coord_equal</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_fill_gradientn</span>(<span class="dt">colours =</span> <span class="kw">c</span>(<span class="st">"#2c7bb6"</span>, <span class="st">"#abd9e9"</span>, <span class="st">"#ffffbf"</span>, <span class="st">"#fdae61"</span>, <span class="st">"#d7191c"</span>),
                         <span class="dt">na.value =</span> <span class="st">"transparent"</span>,
                         <span class="dt">name =</span> <span class="st">'°C x 10'</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">'Annual Mean Temperature'</span>,
         <span class="dt">x =</span> <span class="st">'longitude'</span>,
         <span class="dt">y =</span> <span class="st">'latitude'</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_x_continuous</span>(<span class="dt">expand =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_y_continuous</span>(<span class="dt">expand =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">0</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">theme_minimal</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>),
          <span class="dt">axis.ticks.x =</span> <span class="kw">element_blank</span>(),
          <span class="dt">axis.ticks.y =</span> <span class="kw">element_blank</span>())</code></pre></div>
<p><img src="tune_auc_files/figure-html/unnamed-chunk-2-1.png" width="700" style="display: block; margin: auto;"></p>
<p>There are nine environmental variables:</p>
<ul>
<li>Continuous variables
<ul>
<li>
<strong>bio1</strong> Annual Mean Temperature</li>
<li>
<strong>bio5</strong> Max Temperature of Warmest Month</li>
<li>
<strong>bio6</strong> Min Temperature of Coldest Month</li>
<li>
<strong>bio7</strong> Temperature Annual Range (bio5-bio6)</li>
<li>
<strong>bio8</strong> Mean Temperature of Wettest Quarter</li>
<li>
<strong>bio12</strong> Annual Precipitation</li>
<li>
<strong>bio16</strong> Precipitation of Wettest Quarter</li>
<li>
<strong>bio17</strong> Precipitation of Driest Quarter</li>
</ul>
</li>
<li>Categorical variables
<ul>
<li>
<strong>biome</strong> Terrestrial Ecoregions of the World</li>
</ul>
</li>
</ul>
<p>For demostrating how to use <code>SDMsel</code> we download a dataset of <a href="https://en.wikipedia.org/wiki/Andean_condor"><em>Vultur gryphus</em></a> from the Global Biodiversity Inventory Facility <a href="http://www.gbif.org/">GBIF</a> using the <a href="https://www.rdocumentation.org/packages/dismo/versions/1.1-4/topics/gbif">gbif</a> function of <code>dismo</code> package. We download data from the last 3 years.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">data &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/dismo/topics/gbif">gbif</a></span>(<span class="dt">genus =</span> <span class="st">'Vultur'</span>, <span class="dt">species =</span> <span class="st">'gryphus*'</span>, <span class="dt">geo =</span> <span class="ot">TRUE</span>, <span class="dt">removeZeros =</span> <span class="ot">TRUE</span>, <span class="dt">args =</span> <span class="st">'year=2015,2017'</span>)
<span class="co">#&gt; 4217 records found</span>
<span class="co">#&gt; 0-300-600-900-1200-1500-1800-2100-2400-2700-3000-3300-3600-3900-4200-4217 records downloaded</span>
data &lt;-<span class="st"> </span><span class="kw">data.frame</span>(<span class="dt">x =</span> data<span class="op">$</span>lon, <span class="dt">y =</span> data<span class="op">$</span>lat)
cleaned_data &lt;-<span class="st"> </span>data[<span class="op">!</span><span class="kw">duplicated</span>(data), ]  <span class="co"># Remove duplicate rows</span>
cleaned_data &lt;-<span class="st"> </span>cleaned_data[<span class="op">!</span><span class="kw">is.na</span>(cleaned_data<span class="op">$</span>x) <span class="op">|</span><span class="st"> </span><span class="op">!</span><span class="kw">is.na</span>(cleaned_data<span class="op">$</span>y), ]  <span class="co"># Remove NA values</span></code></pre></div>
<p>We remove all but one location per raster cell using the function <code>thinData</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">cleaned_data &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/thinData.html">thinData</a></span>(cleaned_data, predictors)</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cat</span>(<span class="st">'Number of observations before cleaning data:'</span>, <span class="kw">nrow</span>(data),
    <span class="st">'</span><span class="ch">\n</span><span class="st">Number of obsevations after cleaning data  :'</span>, <span class="kw">nrow</span>(cleaned_data))
<span class="co">#&gt; Number of observations before cleaning data: 4217 </span>
<span class="co">#&gt; Number of obsevations after cleaning data  : 348</span></code></pre></div>
<p>We downloaded 4217 presence locations and after removing the duplicates, the NA and all but one location per raster cell we have 348 locations for our analysis. We can plot the study area and the cleaned locations:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="kw">map_data</span>(<span class="st">'world'</span>), <span class="kw">aes</span>(long, lat)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_polygon</span>(<span class="kw">aes</span>(<span class="dt">group =</span> group), <span class="dt">fill =</span> <span class="st">"grey95"</span>, <span class="dt">color =</span> <span class="st">"gray40"</span>, <span class="dt">size =</span> <span class="fl">0.2</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_jitter</span>(<span class="dt">data =</span> cleaned_data, <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y), <span class="dt">color =</span> <span class="st">'red'</span>,
                <span class="dt">alpha =</span> <span class="fl">0.4</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">"longitude"</span>, <span class="dt">y =</span> <span class="st">"latitude"</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">theme_minimal</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">"none"</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">coord_fixed</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_x_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">125</span>, <span class="op">-</span><span class="dv">32</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">56</span>, <span class="dv">40</span>))</code></pre></div>
<p><img src="tune_auc_files/figure-html/unnamed-chunk-5-1.png" width="700" style="display: block; margin: auto;"></p>
<p>In this tutorial we don’t check the validity of the locations, instead we assume they are correct and we model the distribution only for demonstration purpose.</p>
</div>
<div id="model-selection" class="section level1">
<h1 class="hasAnchor">
<a href="#model-selection" class="anchor"></a>Model Selection</h1>
<p>MaxEnt is a Machine Learning (ML) approach for Species Distribution Models and most of the ML methods require to define several <strong>hyperparameters</strong> before training the model. Hyperparameters are parameters whose values are set before the learning process begins and are not estimated from the data. Their best value is unknown for a given model but can be assessd using a tuning precedure. During the tuning procedure several models are trained varying the value of a hyperparameters and the model with the best performance is retained. The performance of a model can be evaluated using various metrics, <code>SDMsel</code> provides three: <code>AUC</code>, <code>TSS</code> (True Skill Statistic) and <code>AICc</code>.</p>
<div id="prepare-data-for-model-selection" class="section level2">
<h2 class="hasAnchor">
<a href="#prepare-data-for-model-selection" class="anchor"></a>Prepare data for Model Selection</h2>
<p>In this vignette we demonstrate how to perform model selction using the <code>AUC</code>. In ML part of the data are withheld for testing purpose. A model is trained using the majority of the data and then evaluated using the withheld dataset. During hyperparameter tuning this process is repeated several times and the hyperparameters are tuned to improve the prediction on the test dataset. At the end of the model selection process the test dataset doesn’t represent anymore an indipendet sample and then is a good practice to split the data randomly in three parts: <strong>Train</strong>, <strong>Validation</strong> and <strong>Test</strong> datasets <span class="citation">(Russell and Norvig 2009)</span>. The <strong>Train</strong> dataset is used to train the model, the <strong>Validation</strong> dataset to estimate the model performance while tuning the hyperparameters and the <strong>Test</strong> dataset is used at the end of the tuning process to have an unbiased evaluation of the final model. For a good overview of the topic visit the <a href="https://machinelearningmastery.com/difference-test-validation-datasets/">Jason Brownlee’s</a> thread.<br>
We create a random train/val/test datasets withholding a 20% sample for validation and a 20% for testing. We set the seed to obtain consistent results between different trails:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co"># The %&lt;-% operator from "zeallot"" package unpacks a list in variables</span>
<span class="kw">c</span>(train_coords, val_coords, test_coords) <span class="op">%&lt;-%</span><span class="st"> </span><span class="kw"><a href="../../reference/trainValTest.html">trainValTest</a></span>(cleaned_data, <span class="dt">val =</span> <span class="fl">0.2</span>, <span class="dt">test =</span> <span class="fl">0.2</span>, <span class="dt">seed =</span> <span class="dv">2530</span>)
<span class="kw">cat</span>(<span class="st">'Total presence locations  :'</span>, <span class="kw">nrow</span>(cleaned_data),
    <span class="st">'</span><span class="ch">\n</span><span class="st">Total train locations     :'</span>, <span class="kw">nrow</span>(train_coords),
    <span class="st">'</span><span class="ch">\n</span><span class="st">Total validation locations:'</span>, <span class="kw">nrow</span>(val_coords),
    <span class="st">'</span><span class="ch">\n</span><span class="st">Total test locations      :'</span>, <span class="kw">nrow</span>(test_coords))
<span class="co">#&gt; Total presence locations  : 348 </span>
<span class="co">#&gt; Total train locations     : 209 </span>
<span class="co">#&gt; Total validation locations: 70 </span>
<span class="co">#&gt; Total test locations      : 69</span></code></pre></div>
<p>Plot <strong>Train</strong>, <strong>Validation</strong> and <strong>Test</strong> datasets:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">base_plot &lt;-<span class="st"> </span><span class="kw">ggplot</span>(<span class="kw">map_data</span>(<span class="st">'world'</span>), <span class="kw">aes</span>(long, lat)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_polygon</span>(<span class="kw">aes</span>(<span class="dt">group =</span> group), <span class="dt">fill =</span> <span class="st">"grey95"</span>, <span class="dt">color =</span> <span class="st">"gray40"</span>, <span class="dt">size =</span> <span class="fl">0.1</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">"longitude"</span>, <span class="dt">y =</span> <span class="st">"latitude"</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme_minimal</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">"none"</span>) <span class="op">+</span>
<span class="st">  </span><span class="kw">coord_fixed</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_x_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">125</span>, <span class="op">-</span><span class="dv">32</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">56</span>, <span class="dv">40</span>)) <span class="op">+</span>
<span class="st">  </span><span class="kw">theme</span>(<span class="dt">plot.title =</span> <span class="kw">element_text</span>(<span class="dt">hjust =</span> <span class="fl">0.5</span>))

train_plot &lt;-<span class="st"> </span>base_plot <span class="op">+</span><span class="st"> </span><span class="kw">geom_jitter</span>(<span class="dt">data =</span> train_coords, <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y), <span class="dt">color =</span> <span class="st">'red'</span>, <span class="dt">alpha =</span> <span class="fl">0.4</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">'Train'</span>)
val_plot &lt;-<span class="st"> </span>base_plot <span class="op">+</span><span class="st"> </span><span class="kw">geom_jitter</span>(<span class="dt">data =</span> val_coords, <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y), <span class="dt">color =</span> <span class="st">'green'</span>, <span class="dt">alpha =</span> <span class="fl">0.4</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">'Validation'</span>)
test_plot &lt;-<span class="st"> </span>base_plot <span class="op">+</span><span class="st"> </span><span class="kw">geom_jitter</span>(<span class="dt">data =</span> test_coords, <span class="kw">aes</span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y), <span class="dt">color =</span> <span class="st">'blue'</span>, <span class="dt">alpha =</span> <span class="fl">0.4</span>, <span class="dt">size =</span> <span class="dv">1</span>) <span class="op">+</span><span class="st"> </span><span class="kw">labs</span>(<span class="dt">title =</span> <span class="st">'Test'</span>)

<span class="kw"><a href="http://www.rdocumentation.org/packages/gridExtra/topics/arrangeGrob">grid.arrange</a></span>(train_plot, val_plot, test_plot, <span class="dt">nrow =</span> <span class="dv">1</span>)</code></pre></div>
<p><img src="tune_auc_files/figure-html/unnamed-chunk-6-1.png" width="700" style="display: block; margin: auto;"></p>
<p>To extract the background locations we use the <a href="https://www.rdocumentation.org/packages/dismo/versions/1.1-4/topics/randomPoints">randomPoints</a> function from <code>dismo</code> package.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">set.seed</span>(<span class="dv">25</span>)
bg_coords &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/dismo/topics/randomPoints">randomPoints</a></span>(predictors, <span class="dv">10000</span>)
<span class="co">#&gt; Warning in randomPoints(predictors, 10000): generated random points =</span>
<span class="co">#&gt; 0.9775 times requested number</span></code></pre></div>
<p>The environmental variables we downloaded have a coarse resolution and the function cannot extract more than 9775 as you can see from the warning message.</p>
<p>Before running the model we have to prepare the data in the correct format. The <code>prepareSWD</code> function creates a <code>SWD</code> object that stores the species name, the coordinates of the locations and the value of the environmental variables at location points. The parameter <code>categoricals</code> indicates which environmental variables are categorical. In our example <strong>biome</strong> is categorical (you can pass a vector if you have more than one categorical environmental variables). The function extracts the value of the environmental variables for each location and excludes those locations that have <code>NA</code> value for at least one environmental variable.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">train &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/prepareSWD.html">prepareSWD</a></span>(<span class="dt">species =</span> <span class="st">"Vultur gryphus"</span>, <span class="dt">coords =</span> train_coords, <span class="dt">env =</span> predictors, <span class="dt">categoricals =</span> <span class="st">"biome"</span>)
<span class="co">#&gt; Extracting environmental condition for Vultur gryphus...</span>
val &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/prepareSWD.html">prepareSWD</a></span>(<span class="dt">species =</span> <span class="st">"Vultur gryphus"</span>, <span class="dt">coords =</span> val_coords, <span class="dt">env =</span> predictors, <span class="dt">categoricals =</span> <span class="st">"biome"</span>)
<span class="co">#&gt; Extracting environmental condition for Vultur gryphus...</span>
test &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/prepareSWD.html">prepareSWD</a></span>(<span class="dt">species =</span> <span class="st">"Vultur gryphus"</span>, <span class="dt">coords =</span> test_coords, <span class="dt">env =</span> predictors, <span class="dt">categoricals =</span> <span class="st">"biome"</span>)
<span class="co">#&gt; Extracting environmental condition for Vultur gryphus...</span>
bg &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/prepareSWD.html">prepareSWD</a></span>(<span class="dt">species =</span> <span class="st">"Vultur gryphus"</span>, <span class="dt">coords =</span> bg_coords, <span class="dt">env =</span> predictors, <span class="dt">categoricals =</span> <span class="st">"biome"</span>)
<span class="co">#&gt; Extracting environmental condition for Vultur gryphus...</span>
<span class="co">#&gt; Warning: 9 locations are NA for some environmental variables, they will be discard!</span></code></pre></div>
<p>The warning message reports that in the background dataset there are 9 locations that are discarded.<br>
Let’s have a look at the <code>SWD</code> object:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">train
<span class="co">#&gt; Class                : SWD </span>
<span class="co">#&gt; Species              : Vultur gryphus </span>
<span class="co">#&gt; Locations            : 209 </span>
<span class="co">#&gt; Continuous variables : bio1 bio12 bio16 bio17 bio5 bio6 bio7 bio8 </span>
<span class="co">#&gt; Categorical variables: biome</span></code></pre></div>
<p>There are three slots: <code>species</code>, <code>coords</code> and <code>data</code>. To see the data we run:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(train<span class="op">@</span>data)
<span class="co">#&gt;   bio1 bio12 bio16 bio17 bio5 bio6 bio7 bio8 biome</span>
<span class="co">#&gt; 1  136   382   242     7  281   22  259   87    12</span>
<span class="co">#&gt; 2   68  1346   580   160  197  -25  223   20     4</span>
<span class="co">#&gt; 3   37   616   175   123  119  -33  151   37     4</span>
<span class="co">#&gt; 4  193   662   388    11  310   43  267  233     2</span>
<span class="co">#&gt; 5   40   529   151   104  124  -31  155   40     4</span>
<span class="co">#&gt; 6   54   521   169    87  156  -36  192   25     4</span></code></pre></div>
<p>or access the coordinates with <code>train@coords</code> or the species with <code>train@species</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">head</span>(train<span class="op">@</span>coords)
<span class="co">#&gt;             X         Y</span>
<span class="co">#&gt; 326 -70.99844 -33.00903</span>
<span class="co">#&gt; 296 -71.53533 -41.96383</span>
<span class="co">#&gt; 167 -68.09218 -54.71619</span>
<span class="co">#&gt; 292 -64.72847 -25.27307</span>
<span class="co">#&gt; 335 -67.59044 -54.93793</span>
<span class="co">#&gt; 157 -72.48363 -47.11655</span></code></pre></div>
<p>We can save the <code>SWD</code> object in a <strong>.csv</strong> file to use it directly in the software <strong>MaxEnt</strong>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/swd2csv.html">swd2csv</a></span>(train, <span class="dt">file_name =</span> <span class="st">"train.csv"</span>)</code></pre></div>
<p>We use a sub sample of the background locations to train the model and the full dataset to compute the correlation between the environmental variables. We extract the sub sample using the <code>getSubsample</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">bg_model &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/getSubsample.html">getSubsample</a></span>(bg, <span class="dv">5000</span>, <span class="dt">seed =</span> <span class="dv">25</span>)</code></pre></div>
<p>and plot the retained background locations:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="kw">map_data</span>(<span class="st">'world'</span>), <span class="kw">aes</span>(long, lat)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_polygon</span>(<span class="kw">aes</span>(<span class="dt">group =</span> group), <span class="dt">fill =</span> <span class="st">"grey95"</span>, <span class="dt">color =</span> <span class="st">"gray40"</span>, <span class="dt">size =</span> <span class="fl">0.2</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_jitter</span>(<span class="dt">data =</span> bg_model<span class="op">@</span>coords, <span class="kw">aes</span>(<span class="dt">x =</span> X, <span class="dt">y =</span> Y),
                <span class="dt">color =</span> <span class="st">'blue'</span>, <span class="dt">alpha =</span> <span class="fl">0.4</span>, <span class="dt">size =</span> <span class="fl">0.5</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">x =</span> <span class="st">"longitude"</span>, <span class="dt">y =</span> <span class="st">"latitude"</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">theme_minimal</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">theme</span>(<span class="dt">legend.position =</span> <span class="st">"none"</span>) <span class="op">+</span>
<span class="st">    </span><span class="kw">coord_fixed</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_x_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">125</span>, <span class="op">-</span><span class="dv">32</span>)) <span class="op">+</span>
<span class="st">    </span><span class="kw">scale_y_continuous</span>(<span class="dt">limits =</span> <span class="kw">c</span>(<span class="op">-</span><span class="dv">56</span>, <span class="dv">40</span>))</code></pre></div>
<p><img src="tune_auc_files/figure-html/unnamed-chunk-7-1.png" width="700" style="display: block; margin: auto;"></p>
</div>
</div>
<div id="train-maxent-models" class="section level1">
<h1 class="hasAnchor">
<a href="#train-maxent-models" class="anchor"></a>Train MaxEnt models</h1>
<p>The <code>trainMaxent</code> function helps training MaxEnt models in R and gives the possibility to set several arguments. By default the function saves the <strong>MaxEnt</strong> output files in a temporary folder that is sistematically deleted at the end of the script but we can use the parameter <code>folder</code> to specify where to permanently save the output. The next line of code is an example of how to use the function to train a model (note that <code>rm = 1</code>, <code>fc = "lqph"</code> and <code>type = "cloglog"</code> are the default settings of MaxEnt software v. 1.4.1 when you have at least 80 presence locations):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">base_model &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/trainMaxent.html">trainMaxent</a></span>(<span class="dt">presence =</span> train, <span class="dt">bg =</span> bg_model, <span class="dt">rm =</span> <span class="dv">1</span>, <span class="dt">fc =</span> <span class="st">"lqph"</span>, <span class="dt">type =</span> <span class="st">"cloglog"</span>, <span class="dt">test =</span> val, <span class="dt">iter =</span> <span class="dv">500</span>, <span class="dt">folder =</span> <span class="st">"base_model"</span>)</code></pre></div>
<pre><code>#&gt; Loading required namespace: rJava</code></pre>
<p>The main arguments have a dedicated parameter in the function, for all the others we can use the <code>extra_args</code> parameter and pass a vector with the options (e.g. <code>extra_args = c("responsecurves=true", "writeplotdata=true")</code> to plot the response curves in the html file). The function takes care of the environmental variables data type: when we prepared the data we defined <strong>biome</strong> as categorical variable and the information is passed to the <code>trainMaxent</code> function.</p>
<p>The result of the <code>trainMaxent</code> function is an object of class <code>Maxent</code> that stores in different slots the <strong>presence</strong> (or Train) and <strong>background</strong> locations and, if provided, the <strong>test</strong> dataset; MaxEnt <strong>results</strong>, <strong>lambdas</strong> coefficients, <strong>rm</strong>, <strong>fc</strong>, <strong>iterations</strong>, <strong>output type</strong> and the <strong>folder</strong> where is stored the MaxEnt output if provided. We can access this values using <code>model@name_of_the_slot</code>, like <code>model@rm</code> or <code>model@fc</code>. When we call the model object R prints all the parameters we used to train the model and open the <strong>html</strong> file in the browser (only if we save the results permanetly using the parameter <code>folder = my_path</code>).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">base_model
<span class="co">#&gt; Class                : Maxent </span>
<span class="co">#&gt; Species              : Vultur gryphus </span>
<span class="co">#&gt; RM                   : 1 </span>
<span class="co">#&gt; FCs                  : lqph </span>
<span class="co">#&gt; Iterations           : 500 </span>
<span class="co">#&gt; Output type          : cloglog </span>
<span class="co">#&gt; Presence data        : 209 </span>
<span class="co">#&gt; Background data      : 5000 </span>
<span class="co">#&gt; Test data            : 70 </span>
<span class="co">#&gt; Continuous variables : bio1 bio12 bio16 bio17 bio5 bio6 bio7 bio8 </span>
<span class="co">#&gt; Categorical variables: biome</span></code></pre></div>
<div id="variable-importance" class="section level2">
<h2 class="hasAnchor">
<a href="#variable-importance" class="anchor"></a>Variable Importance</h2>
<p>We can see the <strong>percent contribution</strong> and the <strong>permutation importance</strong> of each environmental variable using <code>varImp</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/varImp.html">varImp</a></span>(base_model)
<span class="co">#&gt;   Variable Permutation_importance Percent_contribution</span>
<span class="co">#&gt; 1     bio1                   63.4                 24.6</span>
<span class="co">#&gt; 2     bio7                   16.6                  5.8</span>
<span class="co">#&gt; 3     bio6                    5.0                  0.5</span>
<span class="co">#&gt; 4     bio5                    4.8                 32.5</span>
<span class="co">#&gt; 5    bio17                    3.7                  3.5</span>
<span class="co">#&gt; 6    biome                    2.4                  3.3</span>
<span class="co">#&gt; 7     bio8                    1.8                 22.2</span>
<span class="co">#&gt; 8    bio12                    1.7                  6.1</span>
<span class="co">#&gt; 9    bio16                    0.6                  1.5</span></code></pre></div>
<p>Or plot it using the <code>plotVarImp</code> function (the default color is grey):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/plotVarImp.html">plotVarImp</a></span>(base_model, <span class="dt">type =</span> <span class="st">"perm"</span>, <span class="dt">color =</span> <span class="st">"#159957"</span>)</code></pre></div>
<p><img src="tune_auc_files/figure-html/plot%20model-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Another way to estimate the variable importance is to run a <strong>Jackknife Test</strong>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">jk &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/doJk.html">doJk</a></span>(base_model, <span class="dt">with_only =</span> T, <span class="dt">metric =</span> <span class="st">"auc"</span>)</code></pre></div>
<p>If the model has a test dataset, it returns the train and test AUC, if not it returns only the train AUC</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">jk
<span class="co">#&gt;   Variable Train_AUC_without Train_AUC_withonly Test_AUC_without</span>
<span class="co">#&gt; 1     bio1            0.9677             0.9247           0.9662</span>
<span class="co">#&gt; 2    bio12            0.9686             0.7742           0.9667</span>
<span class="co">#&gt; 3    bio16            0.9693             0.7591           0.9672</span>
<span class="co">#&gt; 4    bio17            0.9679             0.6078           0.9672</span>
<span class="co">#&gt; 5     bio5            0.9665             0.9393           0.9649</span>
<span class="co">#&gt; 6     bio6            0.9673             0.8584           0.9647</span>
<span class="co">#&gt; 7     bio7            0.9678             0.7610           0.9637</span>
<span class="co">#&gt; 8     bio8            0.9680             0.9223           0.9663</span>
<span class="co">#&gt; 9    biome            0.9670             0.8423           0.9647</span>
<span class="co">#&gt;   Test_AUC_withonly</span>
<span class="co">#&gt; 1            0.9120</span>
<span class="co">#&gt; 2            0.7664</span>
<span class="co">#&gt; 3            0.7582</span>
<span class="co">#&gt; 4            0.5832</span>
<span class="co">#&gt; 5            0.9324</span>
<span class="co">#&gt; 6            0.8597</span>
<span class="co">#&gt; 7            0.7148</span>
<span class="co">#&gt; 8            0.9071</span>
<span class="co">#&gt; 9            0.7928</span></code></pre></div>
<p>We can plot the result of the <strong>Jackknife Test</strong> with the <code>plotJk</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/plotJk.html">plotJk</a></span>(jk, <span class="dt">type =</span> <span class="st">"train"</span>, <span class="dt">ref =</span> <span class="kw"><a href="../../reference/auc.html">auc</a></span>(base_model))</code></pre></div>
<p><img src="tune_auc_files/figure-html/plot%20jk-1.png" width="700" style="display: block; margin: auto;"></p>
<p>The red dashed vertical line represents the AUC value of the model trained using all the environmental variables.</p>
</div>
<div id="plot-response-curves" class="section level2">
<h2 class="hasAnchor">
<a href="#plot-response-curves" class="anchor"></a>Plot Response Curves</h2>
<p>The function <code>plotResponse</code> plots the response curve of the given environmental variable:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/plotResponse.html">plotResponse</a></span>(base_model, <span class="dt">variable =</span> <span class="st">'bio1'</span>, <span class="dt">marginal =</span> T, <span class="dt">fun =</span> mean, <span class="dt">rug =</span> T, <span class="dt">clamp =</span> T)</code></pre></div>
<p><img src="tune_auc_files/figure-html/bio12-1.png" width="700" style="display: block; margin: auto;"></p>
<p><strong>bio1</strong> is a continuous variable, <strong>biome</strong> is categorical (in the next graph we plot the univariate response curve):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/plotResponse.html">plotResponse</a></span>(base_model, <span class="dt">variable =</span> <span class="st">'biome'</span>, <span class="dt">marginal =</span> F, <span class="dt">color =</span> <span class="st">'#159957'</span>, <span class="dt">clamp =</span> T)</code></pre></div>
<p><img src="tune_auc_files/figure-html/biome-1.png" width="700" style="display: block; margin: auto;"></p>
<p><code>color</code> allows to change the <strong>color</strong> of the plot and <code>marginal</code> to plot the marginal response curve.</p>
</div>
<div id="plot-roc-curve" class="section level2">
<h2 class="hasAnchor">
<a href="#plot-roc-curve" class="anchor"></a>Plot ROC curve</h2>
<p>The <code>plotROC</code> function plots the ROC curve and display the value of the AUC. Is possible to plot only the Train ROC curve or the Train together with the validation and/or the test one:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/plotROC.html">plotROC</a></span>(base_model, <span class="dt">val =</span> val)</code></pre></div>
<p><img src="tune_auc_files/figure-html/plot%20ROC-1.png" width="700" style="display: block; margin: auto;"></p>
</div>
</div>
<div id="make-prediction" class="section level1">
<h1 class="hasAnchor">
<a href="#make-prediction" class="anchor"></a>Make Prediction</h1>
<p>The function <code>trainMaxent</code> trains a model but doesn’t make any prediction. The <code>predict</code> method makes the prediction:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prediction &lt;-<span class="st"> </span><span class="kw"><a href="http://www.rdocumentation.org/packages/dismo/topics/predict">predict</a></span>(base_model, <span class="dt">data =</span> predictors, <span class="dt">filename =</span> <span class="st">"base_model_prediction"</span>, <span class="dt">format =</span> <span class="st">"GTiff"</span>, <span class="dt">overwrite =</span> T)</code></pre></div>
<p>You can pass as <code>data</code> a <code>data frame</code>, a <code>SWD object</code> or a <a href="https://www.rdocumentation.org/packages/raster/versions/2.6-7/topics/stack">Raster Stack</a>, <a href="https://www.rdocumentation.org/packages/raster/versions/2.6-7/topics/brick">Raster Brick</a> object. In the first case the function returns a vector of prediction, in the second case it returns a raster map that can be saved providing the <code>filename</code> parameter. For big dataset you can provide the parameter <code>progress = "text"</code> to display a progress bar and take advantage of the parallel computation using <code>parallel = T</code>.</p>
<div id="plot-prediction" class="section level2">
<h2 class="hasAnchor">
<a href="#plot-prediction" class="anchor"></a>Plot Prediction</h2>
<p>The prediction can be plotted using any of the <code>plot</code> function in R but the function <code>plotPred</code> provides a way to plot it using the <a href="https://oscarperpinan.github.io/rastervis/">rasterVis</a> package (<code>lt</code> stands for “legend title”):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/plotPred.html">plotPred</a></span>(prediction, <span class="dt">lt =</span> <span class="st">"cloglog output"</span>)</code></pre></div>
<p><img src="tune_auc_files/figure-html/plot%20prediction-1.png" width="700" style="display: block; margin: auto;"></p>
<p>The default colorramp is similar to the usual MaxEnt output, but you can also use different colorramps:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/plotPred.html">plotPred</a></span>(prediction, <span class="dt">colorramp =</span> <span class="kw">c</span>(<span class="st">"#2c7bb6"</span>, <span class="st">"#abd9e9"</span>, <span class="st">"#ffffbf"</span>, <span class="st">"#fdae61"</span>, <span class="st">"#d7191c"</span>), <span class="dt">lt =</span> <span class="st">"cloglog output"</span>)</code></pre></div>
<p><img src="tune_auc_files/figure-html/plot%20prediction%20colorramp-1.png" width="700" style="display: block; margin: auto;"></p>
<p>To get nice combinations of colors for maps visit <a href="http://colorbrewer2.org/">COLORBREWER</a>, the one in this example is the <strong>5-class RdYlBu</strong> colorblind safe and print friendly. Using <code>hr = T</code> you obtain a high resolution plot, useful for publications.</p>
</div>
<div id="plot-presence-absence" class="section level2">
<h2 class="hasAnchor">
<a href="#plot-presence-absence" class="anchor"></a>Plot Presence Absence</h2>
<p>To create a presence absence map we choose a threshold provided by MaxEnt. The function <code>maxentTh</code> provides a list of possible thresholds:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/maxentTh.html">maxentTh</a></span>(base_model)
<span class="co">#&gt;                                                                          threshold</span>
<span class="co">#&gt; Fixed.cumulative.value.1.Cloglog                                         6.500e-03</span>
<span class="co">#&gt; Fixed.cumulative.value.5.Cloglog                                         4.970e-02</span>
<span class="co">#&gt; Fixed.cumulative.value.10.Cloglog                                        1.242e-01</span>
<span class="co">#&gt; Minimum.training.presence.Cloglog                                        6.000e-04</span>
<span class="co">#&gt; X10.percentile.training.presence.Cloglog                                 1.859e-01</span>
<span class="co">#&gt; Equal.training.sensitivity.and.specificity.Cloglog                       1.762e-01</span>
<span class="co">#&gt; Maximum.training.sensitivity.plus.specificity.Cloglog                    1.167e-01</span>
<span class="co">#&gt; Equal.test.sensitivity.and.specificity.Cloglog                           1.187e-01</span>
<span class="co">#&gt; Maximum.test.sensitivity.plus.specificity.Cloglog                        1.107e-01</span>
<span class="co">#&gt; Balance.training.omission..predicted.area.and.value.Cloglog              2.300e-02</span>
<span class="co">#&gt; Balance.training.omission..predicted.area.and.value.area                 1.976e-01</span>
<span class="co">#&gt; Balance.training.omission..predicted.area.and.value.training.omission    1.440e-02</span>
<span class="co">#&gt; Balance.training.omission..predicted.area.and.value.test.omission        0.000e+00</span>
<span class="co">#&gt; Balance.training.omission..predicted.area.and.value.binomial.probability 4.449e-64</span>
<span class="co">#&gt; Equate.entropy.ofed.and.original.distributions.Cloglog                   1.559e-01</span>
<span class="co">#&gt; Equate.entropy.ofed.and.original.distributions.area                      8.460e-02</span>
<span class="co">#&gt; Equate.entropy.ofed.and.original.distributions.training.omission         7.660e-02</span>
<span class="co">#&gt; Equate.entropy.ofed.and.original.distributions.test.omission             1.143e-01</span>
<span class="co">#&gt; Equate.entropy.ofed.and.original.distributions.binomial.probability      0.000e+00</span></code></pre></div>
<p>For example we use the <strong>Maximum training sensitivity plus specificity Cloglog threshold</strong> as parameter for the <code>plotPA</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/plotPA.html">plotPA</a></span>(prediction, <span class="dt">th =</span> <span class="fl">0.0476</span>, <span class="dt">filename =</span> <span class="st">'pa_map'</span>, <span class="dt">overwrite =</span> <span class="ot">TRUE</span>, <span class="dt">format =</span> <span class="st">'GTiff'</span>)</code></pre></div>
<p><img src="tune_auc_files/figure-html/unnamed-chunk-11-1.png" width="700" style="display: block; margin: auto;"></p>
<p>or we can customise the colors using:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/plotPA.html">plotPA</a></span>(prediction, <span class="dt">th =</span> <span class="fl">0.0476</span>, <span class="dt">colors =</span> <span class="kw">c</span>(<span class="st">"#7fbf7b"</span>, <span class="st">"#af8dc3"</span>))</code></pre></div>
<p><img src="tune_auc_files/figure-html/plot%20presence%20absence%20colors-1.png" width="700" style="display: block; margin: auto;"></p>
</div>
</div>
<div id="data-driven-variable-selection" class="section level1">
<h1 class="hasAnchor">
<a href="#data-driven-variable-selection" class="anchor"></a>Data Driven Variable Selection</h1>
<p>Some of the environmental variables used to train our <strong>base_model</strong> are highly correlated. There are two functions that help to visualize if the environmental variables are highly correlated: <code>plotCor</code> and <code>corVar</code>. <code>plotCor</code> builds a correlation matrix heat map (we use all the extracted background points to checks for autocorrelation):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/plotCor.html">plotCor</a></span>(bg, <span class="dt">method =</span> <span class="st">"spearman"</span>, <span class="dt">cor_th =</span> <span class="fl">0.75</span>)</code></pre></div>
<p><img src="tune_auc_files/figure-html/heat%20map-1.png" width="700" style="display: block; margin: auto;"></p>
<p>Using the parameter <code>cor_th</code> the function prints only the values whose absolute values are higher than the given threshold (in this case 0.75). <code>corVar</code> instead creates a data frame with the correlated variables:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/corVar.html">corVar</a></span>(bg, <span class="dt">method =</span> <span class="st">"spearman"</span>, <span class="dt">cor_th =</span> <span class="fl">0.75</span>)
<span class="co">#&gt;    Var1  Var2      value</span>
<span class="co">#&gt; 1  bio1  bio6  0.9513541</span>
<span class="co">#&gt; 2 bio12 bio16  0.9447559</span>
<span class="co">#&gt; 3  bio6  bio7 -0.8734498</span>
<span class="co">#&gt; 4  bio1  bio8  0.8459649</span></code></pre></div>
<p>One possible approach to remove highly correlated variables is to choose a subset of variables based on expert knowledge of the target species. If you don’t know which variable to retain, you can use some kind of data-driven variable selection. The function <code>varSel</code> iterates through several steps: starting from a trained model it checks if the variable ranked as most important (both variable importance ranks are possible: percent contribution and permutation importance) is highly correlated with other variables according to the given method and correlation threshold. In this case it performs a Jaccknife test and among the correlated variables it discards the one that decreases the less the model performance. After it trains another model without the removed variable and checks again for highly correlated variables. The process is repeated until the retained variables are not highly correlated anymore. We suggest to use a very low regularization parameter to perform variable selection, in this case we use 0.001 (see Vignali et al. we add here the publication)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">selected_var_model &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/varSel.html">varSel</a></span>(base_model, bg, <span class="dt">metric =</span> <span class="st">"auc"</span>, <span class="dt">rm =</span> <span class="fl">0.001</span>, <span class="dt">method =</span> <span class="st">"spearman"</span>, <span class="dt">cor_th =</span> <span class="fl">0.75</span>)</code></pre></div>
<p>The function returns the model trained without the correlated variables, if we print the object we see that the function removed <strong>bio6</strong>, <strong>bio7</strong>, <strong>bio8</strong> and <strong>bio16</strong>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">selected_var_model
<span class="co">#&gt; Class                : Maxent </span>
<span class="co">#&gt; Species              : Vultur gryphus </span>
<span class="co">#&gt; RM                   : 1 </span>
<span class="co">#&gt; FCs                  : lqph </span>
<span class="co">#&gt; Iterations           : 500 </span>
<span class="co">#&gt; Output type          : cloglog </span>
<span class="co">#&gt; Presence data        : 209 </span>
<span class="co">#&gt; Background data      : 5000 </span>
<span class="co">#&gt; Test data            : 70 </span>
<span class="co">#&gt; Continuous variables : bio1 bio12 bio17 bio5 </span>
<span class="co">#&gt; Categorical variables: biome</span></code></pre></div>
<p>If we plot the ROC curve we see that after removing the correlated variables the model has still very good performances:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/plotROC.html">plotROC</a></span>(selected_var_model, <span class="dt">val =</span> val)</code></pre></div>
<p><img src="tune_auc_files/figure-html/unnamed-chunk-13-1.png" width="700" style="display: block; margin: auto;"></p>
</div>
<div id="tune-model-hyperparameters" class="section level1">
<h1 class="hasAnchor">
<a href="#tune-model-hyperparameters" class="anchor"></a>Tune model hyperparameters</h1>
<p><code>SDMsel</code> provides a family of functions to tune model hyperparameters. For <code>Maxent</code> models we can tune the <strong>feature combination</strong>, the number of <strong>background locations</strong>, the <strong>regularization multiplier</strong> and the <strong>number of iterations</strong>. All the functions of this family return an object of class <code>SDMtune</code> with two slots, one for the results and one with all the trained models.</p>
<div id="tune-feature-combination" class="section level2">
<h2 class="hasAnchor">
<a href="#tune-feature-combination" class="anchor"></a>Tune feature combination</h2>
<p>We can test the effect of different feature combinations on model performance using the function <code>tuneFC</code>:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tune_fc &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/tuneFC.html">tuneFC</a></span>(selected_var_model, <span class="dt">fcs =</span> <span class="kw">c</span>(<span class="st">"l"</span>, <span class="st">"lq"</span>, <span class="st">"lqp"</span>, <span class="st">"lqh"</span>, <span class="st">"lqph"</span>, <span class="st">"lqpht"</span>), <span class="dt">metric =</span> <span class="st">"auc"</span>)</code></pre></div>
<p>We can display the results with:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tune_fc<span class="op">@</span>results
<span class="co">#&gt;    it   bg rm    fc train_AUC test_AUC diff_AUC</span>
<span class="co">#&gt; 1 500 5000  1     l    0.9433   0.9411   0.0022</span>
<span class="co">#&gt; 2 500 5000  1    lq    0.9503   0.9458   0.0045</span>
<span class="co">#&gt; 3 500 5000  1   lqp    0.9503   0.9458   0.0045</span>
<span class="co">#&gt; 4 500 5000  1   lqh    0.9600   0.9544   0.0056</span>
<span class="co">#&gt; 5 500 5000  1  lqph    0.9612   0.9569   0.0043</span>
<span class="co">#&gt; 6 500 5000  1 lqpht    0.9707   0.9614   0.0093</span></code></pre></div>
<p>or plot them:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/plot_ly">plot_ly</a></span>(tune_fc<span class="op">@</span>results) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/add_trace">add_trace</a></span>(<span class="dt">x =</span> <span class="op">~</span>fc, <span class="dt">y =</span> <span class="op">~</span>train_AUC, <span class="dt">type =</span> <span class="st">"bar"</span>, <span class="dt">name =</span> <span class="st">"Train AUC"</span>, <span class="dt">marker =</span> <span class="kw">list</span>(<span class="dt">color =</span> <span class="st">"#00BFC4"</span>), <span class="dt">text =</span> <span class="op">~</span><span class="kw">paste</span>(<span class="st">"Diff AUC:"</span>, diff_AUC)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/add_trace">add_trace</a></span>(<span class="dt">x =</span> <span class="op">~</span>fc, <span class="dt">y =</span> <span class="op">~</span>test_AUC, <span class="dt">type =</span> <span class="st">"bar"</span>, <span class="dt">name =</span> <span class="st">"Val AUC"</span>, <span class="dt">marker =</span> <span class="kw">list</span>(<span class="dt">color =</span> <span class="st">"#F8766D"</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/layout">layout</a></span>(<span class="dt">xaxis =</span> <span class="kw">list</span>(<span class="dt">title =</span> <span class="st">"Feature Class Combination"</span>), <span class="dt">yaxis =</span> <span class="kw">list</span>(<span class="dt">title =</span> <span class="st">"AUC"</span>), <span class="dt">barmode =</span> <span class="st">"group"</span>, <span class="dt">title =</span> <span class="st">"Model performance"</span>, <span class="dt">legend =</span> <span class="kw">list</span>(<span class="dt">orientation =</span> <span class="st">'h'</span>))</code></pre></div>
<div id="htmlwidget-30ba12d966d106b4b31b" style="width:700px;height:432.632880098888px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-30ba12d966d106b4b31b">{"x":{"visdat":{"36e6a7fd560":["function () ","plotlyVisDat"]},"cur_data":"36e6a7fd560","attrs":{"36e6a7fd560":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"type":"bar","name":"Train AUC","marker":{"color":"#00BFC4"},"text":{},"inherit":true},"36e6a7fd560.1":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"type":"bar","name":"Val AUC","marker":{"color":"#F8766D"},"inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Feature Class Combination","type":"category","categoryorder":"array","categoryarray":["l","lq","lqh","lqp","lqph","lqpht"]},"yaxis":{"domain":[0,1],"automargin":true,"title":"AUC"},"barmode":"group","title":"Model performance","legend":{"orientation":"h"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":[{"name":"Collaborate","icon":{"width":1000,"ascent":500,"descent":-50,"path":"M487 375c7-10 9-23 5-36l-79-259c-3-12-11-23-22-31-11-8-22-12-35-12l-263 0c-15 0-29 5-43 15-13 10-23 23-28 37-5 13-5 25-1 37 0 0 0 3 1 7 1 5 1 8 1 11 0 2 0 4-1 6 0 3-1 5-1 6 1 2 2 4 3 6 1 2 2 4 4 6 2 3 4 5 5 7 5 7 9 16 13 26 4 10 7 19 9 26 0 2 0 5 0 9-1 4-1 6 0 8 0 2 2 5 4 8 3 3 5 5 5 7 4 6 8 15 12 26 4 11 7 19 7 26 1 1 0 4 0 9-1 4-1 7 0 8 1 2 3 5 6 8 4 4 6 6 6 7 4 5 8 13 13 24 4 11 7 20 7 28 1 1 0 4 0 7-1 3-1 6-1 7 0 2 1 4 3 6 1 1 3 4 5 6 2 3 3 5 5 6 1 2 3 5 4 9 2 3 3 7 5 10 1 3 2 6 4 10 2 4 4 7 6 9 2 3 4 5 7 7 3 2 7 3 11 3 3 0 8 0 13-1l0-1c7 2 12 2 14 2l218 0c14 0 25-5 32-16 8-10 10-23 6-37l-79-259c-7-22-13-37-20-43-7-7-19-10-37-10l-248 0c-5 0-9-2-11-5-2-3-2-7 0-12 4-13 18-20 41-20l264 0c5 0 10 2 16 5 5 3 8 6 10 11l85 282c2 5 2 10 2 17 7-3 13-7 17-13z m-304 0c-1-3-1-5 0-7 1-1 3-2 6-2l174 0c2 0 4 1 7 2 2 2 4 4 5 7l6 18c0 3 0 5-1 7-1 1-3 2-6 2l-173 0c-3 0-5-1-8-2-2-2-4-4-4-7z m-24-73c-1-3-1-5 0-7 2-2 3-2 6-2l174 0c2 0 5 0 7 2 3 2 4 4 5 7l6 18c1 2 0 5-1 6-1 2-3 3-5 3l-174 0c-3 0-5-1-7-3-3-1-4-4-5-6z"},"click":"function(gd) { \n        // is this being viewed in RStudio?\n        if (location.search == '?viewer_pane=1') {\n          alert('To learn about plotly for collaboration, visit:\\n https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html');\n        } else {\n          window.open('https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html', '_blank');\n        }\n      }"}],"cloud":false},"data":[{"x":["l","lq","lqp","lqh","lqph","lqpht"],"y":[0.9433,0.9503,0.9503,0.96,0.9612,0.9707],"type":"bar","name":"Train AUC","marker":{"color":"#00BFC4","line":{"color":"rgba(31,119,180,1)"}},"text":["Diff AUC: 0.0022","Diff AUC: 0.0045","Diff AUC: 0.0045","Diff AUC: 0.0056","Diff AUC: 0.0043","Diff AUC: 0.0093"],"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":["l","lq","lqp","lqh","lqph","lqpht"],"y":[0.9411,0.9458,0.9458,0.9544,0.9569,0.9614],"type":"bar","name":"Val AUC","marker":{"color":"#F8766D","line":{"color":"rgba(255,127,14,1)"}},"error_y":{"color":"rgba(255,127,14,1)"},"error_x":{"color":"rgba(255,127,14,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"base_url":"https://plot.ly"},"evals":["config.modeBarButtonsToAdd.0.click"],"jsHooks":[]}</script><p>We want to maximize the AUC in the validation dataset but we want to acccount also for the difference between train AUC and validation AUC. If you hover hover the previous output and you select “compare data on hover” you notice that <strong>lqph</strong> provides the best result, we select this model from the models slot and use it to tune the number of background locations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tuned_fc &lt;-<span class="st"> </span>tune_fc<span class="op">@</span>models[[<span class="dv">5</span>]]</code></pre></div>
</div>
<div id="tune-number-of-background-locations" class="section level2">
<h2 class="hasAnchor">
<a href="#tune-number-of-background-locations" class="anchor"></a>Tune number of background locations</h2>
<p>The model we trained before used 5000 background locations. To test the effect of using different number of background locations on the model performance we can run the function <code>tuneBg</code>. We have a maximum of 9766 locations in the <code>bg</code> object, in the next example we train a sequence of models using 3000, 4000, 5000, 6000, 7000, 8000, 9000, 9766:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tune_bg &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/tuneBg.html">tuneBg</a></span>(tuned_fc, <span class="dt">bg4test =</span> bg, <span class="dt">bgs =</span> <span class="kw">c</span>(<span class="kw">seq</span>(<span class="dv">1000</span>, <span class="dv">9000</span>, <span class="dv">1000</span>), <span class="kw">nrow</span>(bg<span class="op">@</span>data)), <span class="dt">metric =</span> <span class="st">"auc"</span>, <span class="dt">seed =</span> <span class="dv">25</span>)</code></pre></div>
<p>Output:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tune_bg<span class="op">@</span>results
<span class="co">#&gt;     it   bg rm   fc train_AUC test_AUC diff_AUC</span>
<span class="co">#&gt; 1  500 1000  1 lqph    0.9567   0.9542   0.0025</span>
<span class="co">#&gt; 2  500 2000  1 lqph    0.9568   0.9446   0.0122</span>
<span class="co">#&gt; 3  500 3000  1 lqph    0.9612   0.9514   0.0098</span>
<span class="co">#&gt; 4  500 4000  1 lqph    0.9612   0.9569   0.0043</span>
<span class="co">#&gt; 5  500 5000  1 lqph    0.9612   0.9569   0.0043</span>
<span class="co">#&gt; 6  500 6000  1 lqph    0.9608   0.9569   0.0039</span>
<span class="co">#&gt; 7  500 7000  1 lqph    0.9603   0.9566   0.0037</span>
<span class="co">#&gt; 8  500 8000  1 lqph    0.9611   0.9575   0.0036</span>
<span class="co">#&gt; 9  500 9000  1 lqph    0.9607   0.9574   0.0033</span>
<span class="co">#&gt; 10 500 9766  1 lqph    0.9612   0.9580   0.0032</span></code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/plot_ly">plot_ly</a></span>(tune_bg<span class="op">@</span>results) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/add_trace">add_trace</a></span>(<span class="dt">x =</span> <span class="op">~</span>bg, <span class="dt">y =</span> <span class="op">~</span>train_AUC, <span class="dt">type =</span> <span class="st">"scatter"</span>, <span class="dt">mode =</span> <span class="st">"lines+markers"</span>, <span class="dt">name =</span> <span class="st">"Train AUC"</span>, <span class="dt">marker =</span> <span class="kw">list</span>(<span class="dt">color =</span> <span class="st">"#00BFC4"</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/add_trace">add_trace</a></span>(<span class="dt">x =</span> <span class="op">~</span>bg, <span class="dt">y =</span> <span class="op">~</span>test_AUC, <span class="dt">type =</span> <span class="st">"scatter"</span>, <span class="dt">mode =</span> <span class="st">"lines+markers"</span>, <span class="dt">name =</span> <span class="st">"Val AUC"</span>, <span class="dt">marker =</span> <span class="kw">list</span>(<span class="dt">color =</span> <span class="st">"#F8766D"</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/layout">layout</a></span>(<span class="dt">xaxis =</span> <span class="kw">list</span>(<span class="dt">title =</span> <span class="st">"Background locations"</span>), <span class="dt">yaxis =</span> <span class="kw">list</span>(<span class="dt">title =</span> <span class="st">"AUC"</span>), <span class="dt">title =</span> <span class="st">"Model performance"</span>, <span class="dt">legend =</span> <span class="kw">list</span>(<span class="dt">orientation =</span> <span class="st">'h'</span>))</code></pre></div>
<div id="htmlwidget-bbc54400ada70037711a" style="width:700px;height:432.632880098888px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-bbc54400ada70037711a">{"x":{"visdat":{"36e419e62fe":["function () ","plotlyVisDat"]},"cur_data":"36e419e62fe","attrs":{"36e419e62fe":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"type":"scatter","mode":"lines+markers","name":"Train AUC","marker":{"color":"#00BFC4"},"inherit":true},"36e419e62fe.1":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"type":"scatter","mode":"lines+markers","name":"Val AUC","marker":{"color":"#F8766D"},"inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Background locations"},"yaxis":{"domain":[0,1],"automargin":true,"title":"AUC"},"title":"Model performance","legend":{"orientation":"h"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":[{"name":"Collaborate","icon":{"width":1000,"ascent":500,"descent":-50,"path":"M487 375c7-10 9-23 5-36l-79-259c-3-12-11-23-22-31-11-8-22-12-35-12l-263 0c-15 0-29 5-43 15-13 10-23 23-28 37-5 13-5 25-1 37 0 0 0 3 1 7 1 5 1 8 1 11 0 2 0 4-1 6 0 3-1 5-1 6 1 2 2 4 3 6 1 2 2 4 4 6 2 3 4 5 5 7 5 7 9 16 13 26 4 10 7 19 9 26 0 2 0 5 0 9-1 4-1 6 0 8 0 2 2 5 4 8 3 3 5 5 5 7 4 6 8 15 12 26 4 11 7 19 7 26 1 1 0 4 0 9-1 4-1 7 0 8 1 2 3 5 6 8 4 4 6 6 6 7 4 5 8 13 13 24 4 11 7 20 7 28 1 1 0 4 0 7-1 3-1 6-1 7 0 2 1 4 3 6 1 1 3 4 5 6 2 3 3 5 5 6 1 2 3 5 4 9 2 3 3 7 5 10 1 3 2 6 4 10 2 4 4 7 6 9 2 3 4 5 7 7 3 2 7 3 11 3 3 0 8 0 13-1l0-1c7 2 12 2 14 2l218 0c14 0 25-5 32-16 8-10 10-23 6-37l-79-259c-7-22-13-37-20-43-7-7-19-10-37-10l-248 0c-5 0-9-2-11-5-2-3-2-7 0-12 4-13 18-20 41-20l264 0c5 0 10 2 16 5 5 3 8 6 10 11l85 282c2 5 2 10 2 17 7-3 13-7 17-13z m-304 0c-1-3-1-5 0-7 1-1 3-2 6-2l174 0c2 0 4 1 7 2 2 2 4 4 5 7l6 18c0 3 0 5-1 7-1 1-3 2-6 2l-173 0c-3 0-5-1-8-2-2-2-4-4-4-7z m-24-73c-1-3-1-5 0-7 2-2 3-2 6-2l174 0c2 0 5 0 7 2 3 2 4 4 5 7l6 18c1 2 0 5-1 6-1 2-3 3-5 3l-174 0c-3 0-5-1-7-3-3-1-4-4-5-6z"},"click":"function(gd) { \n        // is this being viewed in RStudio?\n        if (location.search == '?viewer_pane=1') {\n          alert('To learn about plotly for collaboration, visit:\\n https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html');\n        } else {\n          window.open('https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html', '_blank');\n        }\n      }"}],"cloud":false},"data":[{"x":[1000,2000,3000,4000,5000,6000,7000,8000,9000,9766],"y":[0.9567,0.9568,0.9612,0.9612,0.9612,0.9608,0.9603,0.9611,0.9607,0.9612],"type":"scatter","mode":"lines+markers","name":"Train AUC","marker":{"color":"#00BFC4","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"line":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[1000,2000,3000,4000,5000,6000,7000,8000,9000,9766],"y":[0.9542,0.9446,0.9514,0.9569,0.9569,0.9569,0.9566,0.9575,0.9574,0.958],"type":"scatter","mode":"lines+markers","name":"Val AUC","marker":{"color":"#F8766D","line":{"color":"rgba(255,127,14,1)"}},"error_y":{"color":"rgba(255,127,14,1)"},"error_x":{"color":"rgba(255,127,14,1)"},"line":{"color":"rgba(255,127,14,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"base_url":"https://plot.ly"},"evals":["config.modeBarButtonsToAdd.0.click"],"jsHooks":[]}</script><p>We obtain the best result using all the background locations, we select this model from the models slot and use it to tune the regularization multiplier.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tuned_bg &lt;-<span class="st"> </span>tune_bg<span class="op">@</span>models[[<span class="dv">10</span>]]</code></pre></div>
</div>
<div id="tune-regularization-multiplier" class="section level2">
<h2 class="hasAnchor">
<a href="#tune-regularization-multiplier" class="anchor"></a>Tune Regularization Multiplier</h2>
<p>In the next step we tune the <code>regularization multiplier</code>. The default regularization multiplier used by MaxEnt is 1, but is not always the best choice. In the next example we test a sequence of regularization multipliers starting from 0.1 till 2.0 with increments of 0.1:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tune_rm &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/tuneRM.html">tuneRM</a></span>(tuned_bg, <span class="dt">rms =</span> <span class="kw">seq</span>(<span class="fl">0.1</span>, <span class="dv">2</span>, <span class="fl">0.1</span>), <span class="dt">metric =</span> <span class="st">"auc"</span>)</code></pre></div>
<p>Output:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tune_rm<span class="op">@</span>results
<span class="co">#&gt;     it   bg  rm   fc train_AUC test_AUC diff_AUC</span>
<span class="co">#&gt; 1  500 9766 0.1 lqph    0.9702   0.9546   0.0156</span>
<span class="co">#&gt; 2  500 9766 0.2 lqph    0.9685   0.9555   0.0130</span>
<span class="co">#&gt; 3  500 9766 0.3 lqph    0.9669   0.9570   0.0099</span>
<span class="co">#&gt; 4  500 9766 0.4 lqph    0.9659   0.9578   0.0081</span>
<span class="co">#&gt; 5  500 9766 0.5 lqph    0.9655   0.9587   0.0068</span>
<span class="co">#&gt; 6  500 9766 0.6 lqph    0.9646   0.9587   0.0059</span>
<span class="co">#&gt; 7  500 9766 0.7 lqph    0.9636   0.9581   0.0055</span>
<span class="co">#&gt; 8  500 9766 0.8 lqph    0.9630   0.9586   0.0044</span>
<span class="co">#&gt; 9  500 9766 0.9 lqph    0.9620   0.9585   0.0035</span>
<span class="co">#&gt; 10 500 9766 1.0 lqph    0.9612   0.9580   0.0032</span>
<span class="co">#&gt; 11 500 9766 1.1 lqph    0.9604   0.9573   0.0031</span>
<span class="co">#&gt; 12 500 9766 1.2 lqph    0.9599   0.9570   0.0029</span>
<span class="co">#&gt; 13 500 9766 1.3 lqph    0.9595   0.9568   0.0027</span>
<span class="co">#&gt; 14 500 9766 1.4 lqph    0.9591   0.9565   0.0026</span>
<span class="co">#&gt; 15 500 9766 1.5 lqph    0.9587   0.9560   0.0027</span>
<span class="co">#&gt; 16 500 9766 1.6 lqph    0.9583   0.9560   0.0023</span>
<span class="co">#&gt; 17 500 9766 1.7 lqph    0.9577   0.9554   0.0023</span>
<span class="co">#&gt; 18 500 9766 1.8 lqph    0.9572   0.9549   0.0023</span>
<span class="co">#&gt; 19 500 9766 1.9 lqph    0.9571   0.9548   0.0023</span>
<span class="co">#&gt; 20 500 9766 2.0 lqph    0.9567   0.9545   0.0022</span></code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/plot_ly">plot_ly</a></span>(tune_rm<span class="op">@</span>results) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/add_trace">add_trace</a></span>(<span class="dt">x =</span> <span class="op">~</span>rm, <span class="dt">y =</span> <span class="op">~</span>train_AUC, <span class="dt">type =</span> <span class="st">"scatter"</span>, <span class="dt">mode =</span> <span class="st">"lines+markers"</span>, <span class="dt">name =</span> <span class="st">"Train AUC"</span>, <span class="dt">marker =</span> <span class="kw">list</span>(<span class="dt">color =</span> <span class="st">"#00BFC4"</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/add_trace">add_trace</a></span>(<span class="dt">x =</span> <span class="op">~</span>rm, <span class="dt">y =</span> <span class="op">~</span>test_AUC, <span class="dt">type =</span> <span class="st">"scatter"</span>, <span class="dt">mode =</span> <span class="st">"lines+markers"</span>, <span class="dt">name =</span> <span class="st">"Val AUC"</span>, <span class="dt">marker =</span> <span class="kw">list</span>(<span class="dt">color =</span> <span class="st">"#F8766D"</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/layout">layout</a></span>(<span class="dt">xaxis =</span> <span class="kw">list</span>(<span class="dt">title =</span> <span class="st">"Regularization multiplier"</span>), <span class="dt">yaxis =</span> <span class="kw">list</span>(<span class="dt">title =</span> <span class="st">"AUC"</span>), <span class="dt">title =</span> <span class="st">"Model performance"</span>, <span class="dt">legend =</span> <span class="kw">list</span>(<span class="dt">orientation =</span> <span class="st">'h'</span>))</code></pre></div>
<div id="htmlwidget-7eabb78e01e382289442" style="width:700px;height:432.632880098888px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-7eabb78e01e382289442">{"x":{"visdat":{"36e21aab9ce":["function () ","plotlyVisDat"]},"cur_data":"36e21aab9ce","attrs":{"36e21aab9ce":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"type":"scatter","mode":"lines+markers","name":"Train AUC","marker":{"color":"#00BFC4"},"inherit":true},"36e21aab9ce.1":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"type":"scatter","mode":"lines+markers","name":"Val AUC","marker":{"color":"#F8766D"},"inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Regularization multiplier"},"yaxis":{"domain":[0,1],"automargin":true,"title":"AUC"},"title":"Model performance","legend":{"orientation":"h"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":[{"name":"Collaborate","icon":{"width":1000,"ascent":500,"descent":-50,"path":"M487 375c7-10 9-23 5-36l-79-259c-3-12-11-23-22-31-11-8-22-12-35-12l-263 0c-15 0-29 5-43 15-13 10-23 23-28 37-5 13-5 25-1 37 0 0 0 3 1 7 1 5 1 8 1 11 0 2 0 4-1 6 0 3-1 5-1 6 1 2 2 4 3 6 1 2 2 4 4 6 2 3 4 5 5 7 5 7 9 16 13 26 4 10 7 19 9 26 0 2 0 5 0 9-1 4-1 6 0 8 0 2 2 5 4 8 3 3 5 5 5 7 4 6 8 15 12 26 4 11 7 19 7 26 1 1 0 4 0 9-1 4-1 7 0 8 1 2 3 5 6 8 4 4 6 6 6 7 4 5 8 13 13 24 4 11 7 20 7 28 1 1 0 4 0 7-1 3-1 6-1 7 0 2 1 4 3 6 1 1 3 4 5 6 2 3 3 5 5 6 1 2 3 5 4 9 2 3 3 7 5 10 1 3 2 6 4 10 2 4 4 7 6 9 2 3 4 5 7 7 3 2 7 3 11 3 3 0 8 0 13-1l0-1c7 2 12 2 14 2l218 0c14 0 25-5 32-16 8-10 10-23 6-37l-79-259c-7-22-13-37-20-43-7-7-19-10-37-10l-248 0c-5 0-9-2-11-5-2-3-2-7 0-12 4-13 18-20 41-20l264 0c5 0 10 2 16 5 5 3 8 6 10 11l85 282c2 5 2 10 2 17 7-3 13-7 17-13z m-304 0c-1-3-1-5 0-7 1-1 3-2 6-2l174 0c2 0 4 1 7 2 2 2 4 4 5 7l6 18c0 3 0 5-1 7-1 1-3 2-6 2l-173 0c-3 0-5-1-8-2-2-2-4-4-4-7z m-24-73c-1-3-1-5 0-7 2-2 3-2 6-2l174 0c2 0 5 0 7 2 3 2 4 4 5 7l6 18c1 2 0 5-1 6-1 2-3 3-5 3l-174 0c-3 0-5-1-7-3-3-1-4-4-5-6z"},"click":"function(gd) { \n        // is this being viewed in RStudio?\n        if (location.search == '?viewer_pane=1') {\n          alert('To learn about plotly for collaboration, visit:\\n https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html');\n        } else {\n          window.open('https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html', '_blank');\n        }\n      }"}],"cloud":false},"data":[{"x":[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2],"y":[0.9702,0.9685,0.9669,0.9659,0.9655,0.9646,0.9636,0.963,0.962,0.9612,0.9604,0.9599,0.9595,0.9591,0.9587,0.9583,0.9577,0.9572,0.9571,0.9567],"type":"scatter","mode":"lines+markers","name":"Train AUC","marker":{"color":"#00BFC4","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"line":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,1.1,1.2,1.3,1.4,1.5,1.6,1.7,1.8,1.9,2],"y":[0.9546,0.9555,0.957,0.9578,0.9587,0.9587,0.9581,0.9586,0.9585,0.958,0.9573,0.957,0.9568,0.9565,0.956,0.956,0.9554,0.9549,0.9548,0.9545],"type":"scatter","mode":"lines+markers","name":"Val AUC","marker":{"color":"#F8766D","line":{"color":"rgba(255,127,14,1)"}},"error_y":{"color":"rgba(255,127,14,1)"},"error_x":{"color":"rgba(255,127,14,1)"},"line":{"color":"rgba(255,127,14,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"base_url":"https://plot.ly"},"evals":["config.modeBarButtonsToAdd.0.click"],"jsHooks":[]}</script><p>The model with the highest validation AUC uses a <code>regularization multiplier</code> equal to 0.5 but at rm = 0.9 we have a lower differece between train and validation AUC with an irrelevant decrease of validation AUC, we select this model from the models slot and use it to tune the number of iterations.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tuned_rm &lt;-<span class="st"> </span>tune_rm<span class="op">@</span>models[[<span class="dv">9</span>]]</code></pre></div>
</div>
<div id="tune-number-of-iterations" class="section level2">
<h2 class="hasAnchor">
<a href="#tune-number-of-iterations" class="anchor"></a>Tune number of iterations:</h2>
<p>The default number of iterations used by the optimization algorithm in MaxEnt is 500. This value is in general good but can be tuned like other hyperparameters. We test a sequence iterations starting from 400 till 2300 with increments of 100:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tune_it &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/tuneIt.html">tuneIt</a></span>(tuned_rm, <span class="dt">its =</span> <span class="kw">seq</span>(<span class="dv">400</span>, <span class="dv">1100</span>, <span class="dv">50</span>), <span class="dt">metric =</span> <span class="st">"auc"</span>)</code></pre></div>
<p>Output:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tune_it<span class="op">@</span>results
<span class="co">#&gt;      it   bg  rm   fc train_AUC test_AUC diff_AUC</span>
<span class="co">#&gt; 1   400 9766 0.9 lqph    0.9620   0.9579   0.0041</span>
<span class="co">#&gt; 2   450 9766 0.9 lqph    0.9621   0.9583   0.0038</span>
<span class="co">#&gt; 3   500 9766 0.9 lqph    0.9620   0.9585   0.0035</span>
<span class="co">#&gt; 4   550 9766 0.9 lqph    0.9621   0.9585   0.0036</span>
<span class="co">#&gt; 5   600 9766 0.9 lqph    0.9621   0.9586   0.0035</span>
<span class="co">#&gt; 6   650 9766 0.9 lqph    0.9621   0.9586   0.0035</span>
<span class="co">#&gt; 7   700 9766 0.9 lqph    0.9621   0.9586   0.0035</span>
<span class="co">#&gt; 8   750 9766 0.9 lqph    0.9620   0.9585   0.0035</span>
<span class="co">#&gt; 9   800 9766 0.9 lqph    0.9620   0.9585   0.0035</span>
<span class="co">#&gt; 10  850 9766 0.9 lqph    0.9620   0.9585   0.0035</span>
<span class="co">#&gt; 11  900 9766 0.9 lqph    0.9620   0.9586   0.0034</span>
<span class="co">#&gt; 12  950 9766 0.9 lqph    0.9619   0.9585   0.0034</span>
<span class="co">#&gt; 13 1000 9766 0.9 lqph    0.9619   0.9586   0.0033</span>
<span class="co">#&gt; 14 1050 9766 0.9 lqph    0.9618   0.9586   0.0032</span>
<span class="co">#&gt; 15 1100 9766 0.9 lqph    0.9618   0.9586   0.0032</span></code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/plot_ly">plot_ly</a></span>(tune_it<span class="op">@</span>results) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/add_trace">add_trace</a></span>(<span class="dt">x =</span> <span class="op">~</span>it, <span class="dt">y =</span> <span class="op">~</span>train_AUC, <span class="dt">type =</span> <span class="st">"scatter"</span>, <span class="dt">mode =</span> <span class="st">"lines+markers"</span>, <span class="dt">name =</span> <span class="st">"Train AUC"</span>, <span class="dt">marker =</span> <span class="kw">list</span>(<span class="dt">color =</span> <span class="st">"#00BFC4"</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/add_trace">add_trace</a></span>(<span class="dt">x =</span> <span class="op">~</span>it, <span class="dt">y =</span> <span class="op">~</span>test_AUC, <span class="dt">type =</span> <span class="st">"scatter"</span>, <span class="dt">mode =</span> <span class="st">"lines+markers"</span>, <span class="dt">name =</span> <span class="st">"Val AUC"</span>, <span class="dt">marker =</span> <span class="kw">list</span>(<span class="dt">color =</span> <span class="st">"#F8766D"</span>)) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw"><a href="http://www.rdocumentation.org/packages/plotly/topics/layout">layout</a></span>(<span class="dt">xaxis =</span> <span class="kw">list</span>(<span class="dt">title =</span> <span class="st">"Number of iterations"</span>), <span class="dt">yaxis =</span> <span class="kw">list</span>(<span class="dt">title =</span> <span class="st">"AUC"</span>), <span class="dt">title =</span> <span class="st">"Model performance"</span>, <span class="dt">legend =</span> <span class="kw">list</span>(<span class="dt">orientation =</span> <span class="st">'h'</span>))</code></pre></div>
<div id="htmlwidget-fed7e73f7659b66a5e7d" style="width:700px;height:432.632880098888px;" class="plotly html-widget"></div>
<script type="application/json" data-for="htmlwidget-fed7e73f7659b66a5e7d">{"x":{"visdat":{"36e7b5259af":["function () ","plotlyVisDat"]},"cur_data":"36e7b5259af","attrs":{"36e7b5259af":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"type":"scatter","mode":"lines+markers","name":"Train AUC","marker":{"color":"#00BFC4"},"inherit":true},"36e7b5259af.1":{"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"x":{},"y":{},"type":"scatter","mode":"lines+markers","name":"Val AUC","marker":{"color":"#F8766D"},"inherit":true}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"xaxis":{"domain":[0,1],"automargin":true,"title":"Number of iterations"},"yaxis":{"domain":[0,1],"automargin":true,"title":"AUC"},"title":"Model performance","legend":{"orientation":"h"},"hovermode":"closest","showlegend":true},"source":"A","config":{"modeBarButtonsToAdd":[{"name":"Collaborate","icon":{"width":1000,"ascent":500,"descent":-50,"path":"M487 375c7-10 9-23 5-36l-79-259c-3-12-11-23-22-31-11-8-22-12-35-12l-263 0c-15 0-29 5-43 15-13 10-23 23-28 37-5 13-5 25-1 37 0 0 0 3 1 7 1 5 1 8 1 11 0 2 0 4-1 6 0 3-1 5-1 6 1 2 2 4 3 6 1 2 2 4 4 6 2 3 4 5 5 7 5 7 9 16 13 26 4 10 7 19 9 26 0 2 0 5 0 9-1 4-1 6 0 8 0 2 2 5 4 8 3 3 5 5 5 7 4 6 8 15 12 26 4 11 7 19 7 26 1 1 0 4 0 9-1 4-1 7 0 8 1 2 3 5 6 8 4 4 6 6 6 7 4 5 8 13 13 24 4 11 7 20 7 28 1 1 0 4 0 7-1 3-1 6-1 7 0 2 1 4 3 6 1 1 3 4 5 6 2 3 3 5 5 6 1 2 3 5 4 9 2 3 3 7 5 10 1 3 2 6 4 10 2 4 4 7 6 9 2 3 4 5 7 7 3 2 7 3 11 3 3 0 8 0 13-1l0-1c7 2 12 2 14 2l218 0c14 0 25-5 32-16 8-10 10-23 6-37l-79-259c-7-22-13-37-20-43-7-7-19-10-37-10l-248 0c-5 0-9-2-11-5-2-3-2-7 0-12 4-13 18-20 41-20l264 0c5 0 10 2 16 5 5 3 8 6 10 11l85 282c2 5 2 10 2 17 7-3 13-7 17-13z m-304 0c-1-3-1-5 0-7 1-1 3-2 6-2l174 0c2 0 4 1 7 2 2 2 4 4 5 7l6 18c0 3 0 5-1 7-1 1-3 2-6 2l-173 0c-3 0-5-1-8-2-2-2-4-4-4-7z m-24-73c-1-3-1-5 0-7 2-2 3-2 6-2l174 0c2 0 5 0 7 2 3 2 4 4 5 7l6 18c1 2 0 5-1 6-1 2-3 3-5 3l-174 0c-3 0-5-1-7-3-3-1-4-4-5-6z"},"click":"function(gd) { \n        // is this being viewed in RStudio?\n        if (location.search == '?viewer_pane=1') {\n          alert('To learn about plotly for collaboration, visit:\\n https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html');\n        } else {\n          window.open('https://cpsievert.github.io/plotly_book/plot-ly-for-collaboration.html', '_blank');\n        }\n      }"}],"cloud":false},"data":[{"x":[400,450,500,550,600,650,700,750,800,850,900,950,1000,1050,1100],"y":[0.962,0.9621,0.962,0.9621,0.9621,0.9621,0.9621,0.962,0.962,0.962,0.962,0.9619,0.9619,0.9618,0.9618],"type":"scatter","mode":"lines+markers","name":"Train AUC","marker":{"color":"#00BFC4","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"line":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null},{"x":[400,450,500,550,600,650,700,750,800,850,900,950,1000,1050,1100],"y":[0.9579,0.9583,0.9585,0.9585,0.9586,0.9586,0.9586,0.9585,0.9585,0.9585,0.9586,0.9585,0.9586,0.9586,0.9586],"type":"scatter","mode":"lines+markers","name":"Val AUC","marker":{"color":"#F8766D","line":{"color":"rgba(255,127,14,1)"}},"error_y":{"color":"rgba(255,127,14,1)"},"error_x":{"color":"rgba(255,127,14,1)"},"line":{"color":"rgba(255,127,14,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.2,"selected":{"opacity":1},"debounce":0},"base_url":"https://plot.ly"},"evals":["config.modeBarButtonsToAdd.0.click"],"jsHooks":[]}</script><p>The AUC changes varying the number of iterations in both Train and Validation datasets. In this case there are not much differences with the default value of 500 iterations (this is not always the case) but using 1050 iterations we obtain a lower difference between Train and Validation AUC, we select this model from the models slot:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tuned_it &lt;-<span class="st"> </span>tune_it<span class="op">@</span>models[[<span class="kw">which.min</span>(tune_it<span class="op">@</span>results<span class="op">$</span>diff_AUC)]]</code></pre></div>
</div>
<div id="remove-less-important-variables" class="section level2">
<h2 class="hasAnchor">
<a href="#remove-less-important-variables" class="anchor"></a>Remove less important variables</h2>
<p>Let’s say that we would like to remove variables with a contribution (permutation or percent) lower than a given threshold. We could simply remove them in a stepwise fashion untill the variable with the lower contribution contributes more than the given threshold or we could remove the variable only if the model performace doesn’t decrease. The function <code>reduceVar</code> performs both approaches, in the next example we demonstrate the second approach.</p>
<p>We print the variable contribution:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/varImp.html">varImp</a></span>(tuned_it)
<span class="co">#&gt;   Variable Permutation_importance Percent_contribution</span>
<span class="co">#&gt; 1     bio5                   74.3                 52.8</span>
<span class="co">#&gt; 2     bio1                   11.4                 30.8</span>
<span class="co">#&gt; 3    biome                    7.4                  5.4</span>
<span class="co">#&gt; 4    bio12                    4.1                  5.2</span>
<span class="co">#&gt; 5    bio17                    2.8                  5.8</span></code></pre></div>
<p>We decide we want to remove the variables with a permutation importance lower than 3% but we do it only if the model performance doesn’t decrease and we use the <strong>AUC</strong> of the Validation dataset to measure the model performance:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tuned_model &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/reduceVar.html">reduceVar</a></span>(tuned_it, <span class="dt">th =</span> <span class="dv">3</span>, <span class="dt">metric =</span> <span class="st">"auc"</span>, <span class="dt">use_jk =</span> T)</code></pre></div>
<p>We print again the variable contribution:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/varImp.html">varImp</a></span>(tuned_model)
<span class="co">#&gt;   Variable Permutation_importance Percent_contribution</span>
<span class="co">#&gt; 1     bio5                   74.3                 52.8</span>
<span class="co">#&gt; 2     bio1                   11.4                 30.8</span>
<span class="co">#&gt; 3    biome                    7.4                  5.4</span>
<span class="co">#&gt; 4    bio12                    4.1                  5.2</span>
<span class="co">#&gt; 5    bio17                    2.8                  5.8</span></code></pre></div>
<p>but <strong>bio17</strong> was not removed because the model without bio17 has lower performance than the one with. We can demonstrate it removing the variable and comparing the <strong>AUC</strong> values on the Validation dataset:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">model_without_bio17 &lt;-<span class="st"> </span><span class="kw"><a href="../../reference/reduceVar.html">reduceVar</a></span>(tuned_it, <span class="dt">th =</span> <span class="dv">3</span>)
<span class="kw"><a href="../../reference/varImp.html">varImp</a></span>(model_without_bio17)
<span class="co">#&gt;   Variable Permutation_importance Percent_contribution</span>
<span class="co">#&gt; 1     bio5                   78.5                 53.7</span>
<span class="co">#&gt; 2    bio12                    9.7                  9.3</span>
<span class="co">#&gt; 3     bio1                    6.2                 31.5</span>
<span class="co">#&gt; 4    biome                    5.6                  5.6</span></code></pre></div>
<p>Compare AUC:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">cat</span>(<span class="st">"Validation AUC with bio17   : "</span>, <span class="kw"><a href="../../reference/auc.html">auc</a></span>(tuned_it, val),
    <span class="st">"</span><span class="ch">\n</span><span class="st">Validation AUC without bio17: "</span>, <span class="kw"><a href="../../reference/auc.html">auc</a></span>(model_without_bio17, val))
<span class="co">#&gt; Validation AUC with bio17   :  0.9585779 </span>
<span class="co">#&gt; Validation AUC without bio17:  0.9575934</span></code></pre></div>
</div>
</div>
<div id="tuned-model" class="section level1">
<h1 class="hasAnchor">
<a href="#tuned-model" class="anchor"></a>Tuned Model</h1>
<p>We can see the final setting of the tuned model printing the model object:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tuned_model
<span class="co">#&gt; Class                : Maxent </span>
<span class="co">#&gt; Species              : Vultur gryphus </span>
<span class="co">#&gt; RM                   : 0.9 </span>
<span class="co">#&gt; FCs                  : lqph </span>
<span class="co">#&gt; Iterations           : 1050 </span>
<span class="co">#&gt; Output type          : cloglog </span>
<span class="co">#&gt; Presence data        : 209 </span>
<span class="co">#&gt; Background data      : 9766 </span>
<span class="co">#&gt; Test data            : 70 </span>
<span class="co">#&gt; Continuous variables : bio1 bio12 bio17 bio5 </span>
<span class="co">#&gt; Categorical variables: biome</span></code></pre></div>
<p>All the functions of the tuning family don’t save the MaxEnt ouput but we could save it using the <code>trainMaxent</code> function and setting all the hyperparameter values according with the previous output. The <code>maxentOutput</code> function makes this step easier, we just have to pass the model and it will set the hyperparameters for us. In addition there are other parameters to add the response curves and the Jackknife test to the html output:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/modelOutput.html">modelOutput</a></span>(tuned_model, <span class="dt">response_curves =</span> T, <span class="dt">jk =</span> T, <span class="dt">threads =</span> <span class="dv">4</span>, <span class="dt">folder =</span> <span class="st">"final_output"</span>)</code></pre></div>
<p>At the end of the tuning process is time to use the <strong>Test</strong> dataset to have an unbiased estimate of the model performance. We use the <code>plotROC</code> function for that:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw"><a href="../../reference/plotROC.html">plotROC</a></span>(tuned_model, <span class="dt">val =</span> val, <span class="dt">test =</span> test)</code></pre></div>
<p><img src="tune_auc_files/figure-html/unnamed-chunk-34-1.png" width="700" style="display: block; margin: auto;"></p>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs" class="references">
<div id="ref-Hijmans2005">
<p>Hijmans, Robert J., Susan E. Cameron, Juan L. Parra, Peter G. Jones, and Andy Jarvis. 2005. “Very high resolution interpolated climate surfaces for global land areas.” <em>International Journal of Climatology</em> 25 (15). Wiley-Blackwell: 1965–78. doi:<a href="https://doi.org/10.1002/joc.1276">10.1002/joc.1276</a>.</p>
</div>
<div id="ref-Olson2001">
<p>Olson, David M., Eric Dinerstein, Eric D. Wikramanayake, Neil D. Burgess, George V. N. Powell, Emma C. Underwood, Jennifer A. D’amico, et al. 2001. “Terrestrial Ecoregions of the World: A New Map of Life on Earth.” <em>BioScience</em> 51 (11). Oxford University Press: 933. doi:<a href="https://doi.org/10.1641/0006-3568(2001)051%5B0933:TEOTWA%5D2.0.CO;2">10.1641/0006-3568(2001)051[0933:TEOTWA]2.0.CO;2</a>.</p>
</div>
<div id="ref-Russell2013">
<p>Russell, Stuart, and Peter Norvig. 2009. <em>Artificial Intelligence A Modern Approach</em>. 3rd ed. Prentice Hall. doi:<a href="https://doi.org/10.1017/S0269888900007724">10.1017/S0269888900007724</a>.</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#set-working-environment">Set working environment</a></li>
      <li><a href="#acquire-environmental-variables-and-species-distribution-data">Acquire environmental variables and species distribution data</a></li>
      <li>
<a href="#model-selection">Model Selection</a><ul class="nav nav-pills nav-stacked">
<li><a href="#prepare-data-for-model-selection">Prepare data for Model Selection</a></li>
      </ul>
</li>
      <li>
<a href="#train-maxent-models">Train MaxEnt models</a><ul class="nav nav-pills nav-stacked">
<li><a href="#variable-importance">Variable Importance</a></li>
      <li><a href="#plot-response-curves">Plot Response Curves</a></li>
      <li><a href="#plot-roc-curve">Plot ROC curve</a></li>
      </ul>
</li>
      <li>
<a href="#make-prediction">Make Prediction</a><ul class="nav nav-pills nav-stacked">
<li><a href="#plot-prediction">Plot Prediction</a></li>
      <li><a href="#plot-presence-absence">Plot Presence Absence</a></li>
      </ul>
</li>
      <li><a href="#data-driven-variable-selection">Data Driven Variable Selection</a></li>
      <li>
<a href="#tune-model-hyperparameters">Tune model hyperparameters</a><ul class="nav nav-pills nav-stacked">
<li><a href="#tune-feature-combination">Tune feature combination</a></li>
      <li><a href="#tune-number-of-background-locations">Tune number of background locations</a></li>
      <li><a href="#tune-regularization-multiplier">Tune Regularization Multiplier</a></li>
      <li><a href="#tune-number-of-iterations">Tune number of iterations:</a></li>
      <li><a href="#remove-less-important-variables">Remove less important variables</a></li>
      </ul>
</li>
      <li><a href="#tuned-model">Tuned Model</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by <a href="https://github.com/sgvignali">Sergio Vignali</a>, <a href="http://www.cb.iee.unibe.ch/about_us/barras_arnaud_gian/index_eng.html">Arnaud Barras</a>, <a href="http://www.cb.iee.unibe.ch/about_us/dr_braunisch_veronika/index_eng.html">Veronika Braunisch</a>, <a href="http://www.cb.iee.unibe.ch/index_eng.html">Conservation Biology</a>.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="http://pkgdown.r-lib.org/">pkgdown</a>.</p>
</div>

      </footer>
</div>

  

  </body>
</html>
