#' MaxEnt Thresholds
#'
#' Returns the value of the thresholds generated by MaxEnt.
#'
#' @param model Maxent object.
#'
#' @examples maxentTh(model)
#' @export
#'
#' @author Sergio Vignali
maxentTh <- function(model) {
  thresholds <- grep(".threshold", rownames(model@results), value = TRUE)
  thresholds <- grep("cumulative.threshold", thresholds, value = TRUE,
                     invert = TRUE)
  labels <- gsub(".threshold", "", thresholds)
  df <- data.frame(threshold = model@results[thresholds, ])
  rownames(df) <- labels
  return(df)
}
