#' MaxEnt Thresholds
#'
#' Returns the value of the thresholds generated by MaxEnt software.
#'
#' @param model \link{SDMmodel} object trained using the "Maxent" method.
#'
#' @examples \dontrun{maxentTh(model)}
#' @export
#'
#' @author Sergio Vignali
maxentTh <- function(model) {

  if (class(model@model) != "Maxent")
    stop("model must be an SDMmodel object trained using the 'Maxent' method!")

  thresholds <- grep(".threshold", rownames(model@model@results), value = TRUE)
  thresholds <- grep("cumulative.threshold", thresholds, value = TRUE,
                     invert = TRUE)
  labels <- gsub(".threshold", "", thresholds)
  df <- data.frame(threshold = model@model@results[thresholds, ])
  rownames(df) <- labels
  return(df)
}
