# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Clamp
#'
#' Clamp a given vector between the provided lower and upper values.
#'
#' @param x numeric. Vector to be clamped.
#' @param lower numeric. The lowest value used to clamp.
#' @param upper numeric. The highest value used to clamp
#'
#' @details The code is taken from
#' \url{http://gallery.rcpp.org/articles/sugar-function-clamp/}.
#'
#' @return numeric. The clamped vector.
#' @export
#'
#' @examples clamp(1:20, 4, 17)
#'
#' @author Sergio Vignali
clamp <- function(x, lower, upper) {
    .Call('_SDMsel_clamp', PACKAGE = 'SDMsel', x, lower, upper)
}

