# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' One Hot Encoding
#'
#' Converts a factor in One Hot matrix
#' @param x factor. Factor to be encoded
#' @param levels character. Levels to be encoded.
#'
#' @return matrix with the One Hot encoded values
#' @export
#'
#' @examples one_hot(1:10, c("1", "7"))
#' @author Sergio Vignali
#'
one_hot <- function(x, levels) {
    .Call('_SDMsel_one_hot', PACKAGE = 'SDMsel', x, levels)
}

#' Clamp
#'
#' Clamp a given vector between the provided lower and upper values.
#'
#' @param x numeric. Vector to be clamped.
#' @param lower numeric. The lowest value used to clamp.
#' @param upper numeric. The highest value used to clamp
#'
#' @details The code is taken from
#' \url{http://gallery.rcpp.org/articles/sugar-function-clamp/}.
#'
#' @return numeric. The clamped vector.
#' @export
#'
#' @examples clamp(1:20, 4, 17)
#'
#' @author Sergio Vignali
clamp <- function(x, lower, upper) {
    .Call('_SDMsel_clamp', PACKAGE = 'SDMsel', x, lower, upper)
}

