# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scaleClamp <- function(x, min, max, do_clamp, scale) {
    .Call('_SDMtune_scaleClamp', PACKAGE = 'SDMtune', x, min, max, do_clamp, scale)
}

